version: '3'

services:
  database:
    image: postgres:17.4-bookworm
    restart: always
    ports:
      - ${POSTGRES_CONNECT_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DBNAME: ${POSTGRES_DBNAME}
    networks:
      - database-network
    volumes:
      - ${PWD}/db-data/:/var/lib/postgresql/data/
      - ${PWD}/db-init/:/docker-entrypoint-initdb.d/

networks: 
  database-network:
    driver: bridge
