version: '3'

services:
  database:
    image: postgres:17.4-bookworm
    restart: always
    ports:
      - ${POSTGRES_CONNECT_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DBNAME: ${POSTGRES_DBNAME}
    networks:
      - database-network
    volumes:
      - ${PWD}/volumes/db-data/:/var/lib/postgresql/data/
      - ${PWD}/db-init/:/docker-entrypoint-initdb.d/

  server:
    build:
      context: ./go-src/
      dockerfile: Dockerfile
    depends_on:
      - database
    restart: always
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DBNAME: ${POSTGRES_DBNAME}
      POSTGRES_CONNECT_PORT: ${POSTGRES_CONNECT_PORT}
      SERVER_PORT: ${SERVER_PORT}
      DOCUMENTS_PATH: ${DOCUMENTS_PATH}
    networks:
      - database-network
    volumes:
      - ${PWD}/volumes/documents:${DOCUMENTS_PATH}

networks: 
  database-network:
    driver: bridge
