version: '3'

services:
  database:
    image: postgres:17.4-bookworm
    restart: always
    ports:
      - 8000:5432
    env_file:
      - .env
    networks:
      - database-network
    volumes:
      - ${PWD}/db-data/:/var/lib/postgresql/data/
      - ${PWD}/db-init/:/docker-entrypoint-initdb.d/

networks: 
  database-network:
    driver: bridge
