FROM golang:1.24.2-bookworm

WORKDIR /usr/src/app

COPY go-src/go.mod go-src/go.sum go-src/*.go .
RUN go mod download
RUN go build -v -o /usr/local/bin/app .

RUN mkdir -p /usr/var/lib/cms_server

CMD ["app"]