# предварительно нжно поместить фронт в папку front внутри папки с бэком
# Этап сборки фронтенда
FROM node:23.11.0-bookworm AS frontend-build
WORKDIR /frontend
COPY front/package.json front/package-lock.json ./
RUN npm install
COPY front .
RUN npm run build

# Этап сборки бэкенда
FROM golang:1.24.2-bookworm
WORKDIR /app

# Копируем Go-модули
COPY go-src/go.mod go-src/go.sum ./
RUN go mod download

# Копируем исходный код
COPY go-src/*.go .
RUN go build -v -o /usr/local/bin/app .

# Копируем собранный фронтенд
COPY --from=frontend-build /frontend/dist ./dist

RUN mkdir -p /usr/var/lib/cms_server
CMD ["/usr/local/bin/app"]